name: build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

env:
  GITHUb_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - target: aarch64-apple-darwin
          #   os: macos-15
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "stable"

      - uses: cargo-bins/cargo-binstall@main
      - name: install cargo-pgo
        run: |
          cargo binstall cargo-pgo --force --no-confirm
          rustup component add llvm-tools-preview
      - name: ubuntu install llvm
        if: "startsWith(matrix.os, 'ubuntu')"
        run: |
          sudo apt update -y
          sudo apt install llvm -y

      - name: macos install llvm
        if: "startsWith(matrix.os, 'macos')"
        run: |
          brew install llvm
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
          echo "$(brew --prefix llvm)/bin/llvm-profdata" >> $GITHUB_PATH
          echo "LDFLAGS=-L/usr/local/opt/llvm/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/local/opt/llvm/include" >> $GITHUB_ENV

      - name: llvm version
        run: |
          llvm-profdata --version
          which llvm-profdata
      - name: build-${{ matrix.target }}
        run: |
          bash build.sh ${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rqjs-pgo-${{ matrix.target }}
          path: ./rqjs-pgo-${{ matrix.target }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: rqjs-pgo
          pattern: rqjs-pgo*
          merge-multiple: true

      - name: release
        uses: ncipollo/release-action@v1
        with:
          tag: nightly
          artifacts: "rqjs-pgo/*.tar.gz"
          allowUpdates: true
